### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by duck7000** [duck7000/MusicBrainzPHP#9]
@GeorgeFive

Do you think this is ready for a release version?

I think it is pretty much ready for its first release but you might have still issues or requests?

**Comment by GeorgeFive** [comment]
I don't know of any problems right off, no requests that I can think of.  I did put together my database schema this morning, and everything was logical except for the missing secondary types on albums.

I am thinking of adding last.fm functionality into my own setup for artist images, I'm not sure if you have any interest in that?  I assume not, but throwing that out there.

https://github.com/lastfm-docs/api-docs/blob/master/docs/artist/search.md

Otherwise... I'll probably find something as I finish up the coding side of things, but off the top of my head, it seems release ready!

**Comment by duck7000** [comment]
No i  don't think i want/need artist images, and including another api call from a different source is not within the scope of this library and may confuse users i guess.

Maybe lastFm will be the next project haha

Okay i will make the first release and if there still are issues or requests we can deal with that later on.
At least we have a stable base to work with.

Thanks for all your testing though.
